---

ttt_api_path: "/var/www/api-ttt.local/"
ttt_api_url: "api-api.local"
ttt_www_path: "/var/www/ttt.local/"
ttt_www_url: "ttt.local"
ttt_database_name: "ojp"
ttt_env: "dev"

database_username: "root"
database_password: ""
database_hostname: "localhost"
