---

- name: Git checkout
  git:
    repo: "https://github.com/linusnorton/php-journey-planner.git"
    dest: "{{ttt_api_path}}/../"
    update: "no"
  when: git_checkout is defined and git_checkout

- name: NPM packages install
  npm:
    path: "{{ ttt_www_path }}"
  ignore_errors: yes

- name: Composer install
  composer:
    command: install
    working_dir: "{{ ttt_api_path }}"

- name: Create database
  mysql_db:
    name: "{{ ttt_database_name }}"
    state: present
  when: create_database is defined and create_database

- name: Create environment profile
  template:
    src: templates/profile.sh.j2
    dest: /etc/profile.d/traintickets.to.sh
  notify:
    - reload profile

- name: Create server config
  template:
    src: templates/nginx.conf.j2
    dest: /etc/nginx/conf.d/traintickets.to.conf
  notify:
   - reload nginx

- name: Remove default site
  file:
    state: absent
    path: /etc/nginx/conf.d/default.conf
  notify:
   - reload nginx
