---

- name: Install PHP
  apt:
    state: present
    update_cache: yes
    cache_valid_time: 11400
    pkg: "{{ item }}"
  with_items:
    - php
    - php-mysql
    - php-fpm
    - php-xml
    - php-zip

- name: PHP FPM config
  lineinfile:
    dest: /etc/php/7.0/fpm/php.ini
    regexp: ^cgi.fix_pathinfo=1
    line: cgi.fix_pathinfo=0
    backrefs: yes
  notify:
    - reload php7.0-fpm

- name: Switch FPM to TCP
  lineinfile:
    dest: /etc/php/7.0/fpm/pool.d/www.conf
    regexp: "^listen = /run/php/php7.0-fpm.sock"
    line: "listen = 127.0.0.1:9000"
    backrefs: yes
  notify:
    - reload php7.0-fpm

- name: Use all the memory
  lineinfile:
    dest: /etc/php/7.0/fpm/php.ini
    regexp: "^memory_limit = 128"
    line: "memory_limit = 512M"
    backrefs: yes
  notify:
    - reload php7.0-fpm

- name: Check if Composer is installed
  stat: "path=/usr/local/bin/composer"
  register: composer_bin

- name: Download Composer installer
  get_url:
    url: https://getcomposer.org/installer
    dest: /tmp/composer-installer.php
    mode: 0755
  when: not composer_bin.stat.exists

- name: Download Composer installer.
  get_url:
    url: https://getcomposer.org/installer
    dest: /tmp/composer-installer.php
    mode: 0755
  when: not composer_bin.stat.exists

- name: Install Composer
  shell: >
    php /tmp/composer-installer.php --install-dir=/usr/local/bin --filename=composer
    creates=/usr/local/bin/composer
  when: not composer_bin.stat.exists
