---

- hosts: "dev-ttt"
  become: yes
  become_method: sudo
  roles:
    - { role: common, tags: common }
    - { role: mariadb, tags: mariadb }
    - { role: traintickets.to, tags: traintickets.to }

- hosts: "live"
  become: yes
  become_method: sudo
  roles:
    - { role: common, tags: common }
    - { role: traintickets.to, tags: traintickets.to }
